import { CVData } from "./types";

export const cvDataEn: CVData = {
  name: "ARMANDO ANTONIO GONZÁLEZ TAPIADOR",
  title: "BIM Manager / PMP Certified Project Coordinator & Director",
  contact: {
    location: "Alicante, Spain",
    phone: "+34 666 77 61 78",
    email: "arq.nate@gmail.com",
    linkedin: "linkedin.com/in/armando-gonzalez-tapiador",
    photo: "https://media.licdn.com/dms/image/v2/D4D03AQEW8hzfDwtP8A/profile-displayphoto-shrink_800_800/B4DZSzL4cLHkAc-/0/1738173025110?e=1775692800&v=beta&t=GzVQ_npAg3v4AuVE6Yr-8slyTcuNGm_Hratov_YpwCY",
  },
  summary: "• BIM Manager / PMP Certified Project Coordinator & Director with 5+ years of experience delivering high-complexity international projects across Healthcare, Hyperscale Data Centers, Infrastructure, Scientific, Sports, and Defense sectors.\n• Over €10 Billion in cumulative program value and 500,000+ sqm of coordinated built area.\n• Department-level operations management under PMBOK / ISO 21502 / ISO 19650 frameworks—compassing BEP lifecycle management, talent acquisition, client ICE sessions, and QA governance.\n• Multidisciplinary team leader (up to 16 members) on concurrent megaprojects in bilingual (English/Spanish) environments, acting as a trusted liaison between executive management, engineering teams, and Tier-1 clients.",
  experience: [
    {
      dates: "2025-08 to Present",
      duration: "Ongoing",
      company: "Germania de Instalaciones",
      sector: "MEP Subcontractor",
      role: "MEP BIM Coordinator",
      location: "Alicante, Spain",
      project: "Orihuela Hospital Expansion (~45,000sqm | ~€70M) - Vega Baja Health Department",
      summary: "• Sole BIM resource for Germania's MEP HVAC scope on a €70M healthcare expansion (contractual chain: Valnu → Rover → Germania), providing end-to-end coordination: rooftop mechanical systems modeling, phased quantification (as-built vs. pending), and on-site verification ensuring fidelity to the executed design.\n• Defined minimum functional BIM standards (LoIN/BEP) tailored to operational needs, managing federated model workflows for data-driven procurement and supply chain validation.",
      reasonForLeaving: "N/A - Current Position",
    },
    {
      dates: "2025-05 to 2025-08",
      duration: "4 months",
      company: "NTI Spain",
      sector: "BIM Consulting / Autodesk Platinum Partner",
      role: "AEC BIM Consultant",
      location: "Madrid, Spain",
      project: "Various Tier-1 Architecture & Engineering Clients",
      summary: "• Assessed clients' BIM workflows and digital maturity levels to architect targeted demonstrations, training, and adoption strategies—positioning Environment for Revit, NTI for Revit, and Realtime LCA via Speckle for full-lifecycle carbon assessments.\n• Prepared firms for the mandatory EPBD recast (EU 2024/1275) and Level(s) WLC reporting obligations effective 2028.\n• Advised on ISO 19650/CDE implementations and multidisciplinary coordination to elevate internal delivery standards.",
      reasonForLeaving: "Accepted offer to return to Germania for a large-scale hospital project.",
    },
    {
      dates: "2024-11 to 2025-05",
      duration: "7 months",
      company: "Exceltic",
      sector: "Engineering Consultancy",
      role: "BIM Architect / MEP Specialist",
      location: "Spain",
      project: "Hyperscale Data Centers (~20,000sqm IT per facility | ~€6-10B Regional Program) - Microsoft & Amazon / NATO Defense Infrastructure (~250,000sqm | ~€0.8B) via AECOM",
      summary: "• Produced MEP technical design packages and spatial coordination (LOD 300-350) in English and Spanish for mission-critical hyperscale data centers and defense infrastructure, under AECOM frameworks, USACE standards, and NDA-bound security protocols.\n• Controlled delivery milestones across staged deliverables (30/60/90/100%).",
      reasonForLeaving: "Project phase completion; transitioned to BIM consultancy with management support.",
    },
    {
      dates: "2024-09 to 2024-10",
      duration: "2 months",
      company: "ADYD Group",
      sector: "Engineering Consultancy",
      role: "BIM Architect",
      location: "Spain / Belgium",
      project: "NATO Defense Infrastructure (~250,000sqm | ~€0.8B) - Belgium via AECOM",
      summary: "• Rapid-deployment BIM design and coordination for NATO defense facilities under AECOM/USACE protocols.\n• Managed staggered deliverables in a bilingual environment, ensuring long-term engagement continuity.",
      reasonForLeaving: "External workforce reduction by AECOM; rejoined a broader MEP role via Exceltic.",
    },
    {
      dates: "2024-08 to 2024-09",
      duration: "2 months",
      company: "Germania de Instalaciones",
      sector: "MEP Subcontractor",
      role: "MEP BIM Modeler / CAD",
      location: "Madrid, Spain",
      project: "Various Residential, Transport Interchanges, and Industrial Facilities",
      summary: "• Supported pre-construction workflows by drafting MEP spatial layouts in CAD, production drawings, and manual take-offs across multiple concurrent, fast-paced projects.",
      reasonForLeaving: "Transitioned to an international defense project role with broader technical scope.",
    },
    {
      dates: "2024-06 to 2024-08",
      duration: "3 months",
      company: "EAG (GHESA) via Plenum",
      sector: "Engineering Consultancy",
      role: "BIM Architect",
      location: "Spain",
      project: "Spotify Camp Nou Remodeling (~300,000sqm | ~€1.3B) - FC Barcelona — Europe's largest football stadium",
      summary: "• Directed Plenum’s on-site modeling team at GHESA, ensuring the quality of architectural BIM production deliverables within a high-density federated model, governed by ISO 19650 workflows and CDE.\n• Provided continuous remote technical support post-deployment to ensure operational stability.\n• Assignment encompassed Modeler and BIM Manager roles within Plenum.",
      reasonForLeaving: "Reassigned to other high-priority projects within Plenum's outsourcing network.",
    },
    {
      dates: "2023-06 to 2024-08",
      duration: "1 year 2 months (14 months)",
      company: "Plenum Ingenieros",
      sector: "BIM Consulting & Outsourcing",
      role: "BIM Manager / Head of Operations",
      location: "Spain",
      project: "Fehmarnbelt Fixed Link — world’s longest immersed road and rail tunnel (18km | ~€7.4B), Palacio del Marqués de Salamanca Heritage HQ (~25,000sqm | ~€50M), UCM Mathematics Faculty (~15,000sqm)",
      summary: "• Directed department-level BIM operations under PMBOK / ISO 21502 / Agile, managing 4 concurrent international megaprojects valued at over €7 Billion.\n• Managed the full ISO 19650 lifecycle—validating and re-implementing BEPs, defining LoINs, administering CDEs, assessing bidding capabilities, and leading talent acquisition for a 16-person multidisciplinary team (Architecture, Structure, MEP).\n• Handled Open BIM coordination for 22 Fehmarnbelt tunnel segments with Kanban-based scheduling, reporting directly to IDOM's senior BIM Managers.\n• Enforced QA across all English/Spanish deliverables, defended federated models in client ICE sessions, and resolved critical interoperability bottlenecks, driving department productivity.",
      reasonForLeaving: "Tunnel project stalled due to pending engineering data; maintained strong executive trust.",
    },
    {
      dates: "2022-07 to 2023-06",
      duration: "11 months",
      company: "Plenum Ingenieros",
      sector: "BIM Consulting & Outsourcing",
      role: "MEP BIM Modeler / Architect",
      location: "Spain",
      project: "IDOM (Giant Magellan Telescope ~€1.7B, Basurto/Donostia Hospitals ~380,000sqm | ~€550M), ACH Dakar Hospital (~40,000sqm | ~€135M), ARUP Hotels (~10,000sqm | ~€40M), GHESA/Limak (Camp Nou)",
      summary: "• Lead technical resource across an extreme volume of concurrent projects in Healthcare, Scientific, Hospitality, Sports, Residential, Industrial, and Transport sectors—executing MEP and architectural coordination under relentless deadlines.\n• Proactively assumed BIM management responsibilities due to the existing BIM Manager's saturation, directly coordinating the Camp Nou engagement and providing on-site support in Barcelona.\n• Specified, procured, and deployed critical IT server infrastructure, resolving data bottlenecks in large-scale concurrent models.\n• Trusted PMP advisor to the company owner on strategic and operational decisions.\n• Developed standardized libraries and automation workflows that became core department assets, earning an accelerated promotion to BIM Manager backed by the entire team.",
      reasonForLeaving: "Promoted to BIM Manager / Head of Operations.",
    },
    {
      dates: "2020-07 to 2021-07",
      duration: "1 year",
      company: "Ferrocerámica Valcro",
      sector: "Real Estate Developer / Constructor",
      role: "BIM Architect",
      location: "Venezuela",
      project: "Isla Multiespacio High-Rise (~90,000sqm | ~€150M) and Cameva Retail Chain (~20,000sqm | ~€30M Aggregate)",
      summary: "• Produced comprehensive structural and architectural BIM documentation for mixed-use projects—drawings, sections, construction details, renderings, visualizations, and material take-offs.\n• Conducted regular on-site construction supervision ensuring fidelity between design and execution.\n• Led cross-platform coordination with ArchiCAD counterparts, gaining foundational experience in IFC/Open BIM workflows.",
      reasonForLeaving: "Left to pursue a Master's degree in Integrated Project Management.",
    },
  ],
  earlierExperience: [
    { role: "Architectural Project Director", company: "AESTUDIO", year: "2022" },
    { role: "Freelance Architect", company: "Freelance", year: "2021" },
    { role: "Editor (Spanish-English)", company: "XiaomiToday", year: "2017–2018" },
    { role: "Architect Intern", company: "ARCOS 5", year: "2017" },
  ],
  technicalSkills: [
    { category: "BIM & Coordination", skills: ["Revit (MEP, Architecture, Structure) – Expert", "Navisworks", "AutoCAD 2D/3D"] },
    { category: "Automation & Programming", skills: ["Dynamo", "Python", "Computer Science Curriculum C 42 Madrid (Ongoing)"] },
    { category: "Reality Capture", skills: ["Scan-to-BIM Workflows", "Point Cloud Integration (LIDAR)"] },
    { category: "Project & Cost Management", skills: ["Microsoft Project", "CYPE", "Presto"] },
    { category: "Visualization", skills: ["3Ds Max", "V-Ray", "Lumion", "Twinmotion", "D5"] },
    { category: "Other", skills: ["CDE Environments (ACC)", "IT Infrastructure Management", "Technical Consulting"] },
  ],
  education: [
    { degree: "Master in Integrated Project Management (PMP)", institution: "University of A Coruña – Spain" },
    { degree: "Bachelor of Architecture", institution: "I.U.P.S.M. Maracay – Venezuela (HOMOLOGATION ANECA SPAIN)" },
    { degree: "Computer Science (Ongoing)", institution: "42 Madrid - Spain" },
  ],
  awards: [
    { title: "Recognition for Foreign Excellence", issuer: "Xunta de Galicia (Spain)", year: "2022", description: "Awarded for undertaking the Master in Integrated Project Management (PMP) abroad" },
  ],
  certifications: [
    "Autodesk Revit Architecture Expert",
    "Autodesk Revit MEP Coordinator",
    "BIM Project Management – Confemetal Foundation",
  ],
  languages: [
    { language: "Spanish", level: "Native" },
    { language: "English", level: "Bilingual" },
  ],
};
