import { CVData } from "./types";

export const cvData: CVData = {
  name: "ARMANDO ANTONIO GONZÁLEZ TAPIADOR",
  title: "BIM Manager / Coordinador y Director de Proyectos PMP",
  contact: {
    location: "Alicante, España",
    phone: "+34 666 77 61 78",
    email: "arq.nate@gmail.com",
    linkedin: "linkedin.com/in/armando-gonzalez-tapiador",
    photo: "https://media.licdn.com/dms/image/v2/D4D03AQEW8hzfDwtP8A/profile-displayphoto-shrink_800_800/B4DZSzL4cLHkAc-/0/1738173025110?e=1775692800&v=beta&t=GzVQ_npAg3v4AuVE6Yr-8slyTcuNGm_Hratov_YpwCY",
  },
  summary: "• Dirección de operaciones BIM a escala departamental (PMBOK / ISO 21502 / ISO 19650).\n• Gestión concurrente de megaproyectos internacionales (Data Centers, Infraestructura, Salud) valorados en >€10.000M.\n• Liderazgo técnico y adquisición de talento para equipos multidisciplinarios (hasta 16 miembros) en entornos CDE.\n• Creación de herramientas (Python/Dynamo) para QA federado y automatización de procesos.",
  experience: [
    {
      dates: "2025-08 a la actualidad",
      duration: "En curso",
      company: "Germania de Instalaciones",
      sector: "Subcontratista MEP",
      role: "Coordinador BIM MEP",
      location: "Alicante, España",
      project: "Ampliación del Hospital de Orihuela (~45.000m² | ~€70M)",
      summary: "• Coordinación BIM end-to-end (HVAC) para proyecto hospitalario liderado por UTE Rover.\n• Implementación de estándares BIM (LoIN/BEP) optimizados para fabricación y obra.\n• Generación de mediciones precisas a partir del modelo federado para justificación financiera de certificaciones de obra.",
      reasonForLeaving: "N/A - Puesto actual",
    },
    {
      dates: "2025-05 a 2025-08",
      duration: "4 meses",
      company: "NTI Spain",
      sector: "Consultoría BIM / Autodesk Platinum",
      role: "Consultor BIM AEC",
      location: "Madrid, España",
      project: "Diversos perfiles Tier 1 (AEC)",
      summary: "• Diagnóstico de madurez BIM y estrategia de adopción de software para empresas del sector.\n• Implementación de metodologías para Life Cycle Assessment (LCA) e informes de carbono (EPBD UE).\n• Auditoría de modelos y flujos de trabajo bajo norma ISO 19650.",
      reasonForLeaving: "Acepté oferta para proyecto hospitalario de gran escala (Germania).",
    },
    {
      dates: "2024-11 a 2025-05",
      duration: "7 meses",
      company: "Exceltic",
      sector: "Consultoría de Ingeniería",
      role: "Arquitecto BIM / Especialista MEP",
      location: "España",
      project: "Centros de Datos Hyperscale (~€6-10B) & Infraestructura Defensa OTAN (~€0.8B)",
      summary: "• Diseño técnico y coordinación espacial MEP (LOD 300-350) para proyectos clasificados / NDA.\n• Producción de entregables BIM bajo estándares USACE y AECOM.\n• Aseguramiento de calidad en entregas escalonadas (30/60/90/100%) en inglés.",
      reasonForLeaving: "Finalización de fase; reorientación a consultoría técnica corporativa.",
    },
    {
      dates: "2024-09 a 2024-10",
      duration: "2 meses",
      company: "ADYD Group",
      sector: "Consultoría de Ingeniería",
      role: "Arquitecto BIM",
      location: "España / Bélgica",
      project: "Defensa OTAN (~250.000m² | ~€0.8B)",
      summary: "• Modelado BIM MEP de despliegue rápido bajo protocolos AECOM (Inglés).\n• Integración en equipos deslocalizados para diseño crítico en plazos ajustados.",
      reasonForLeaving: "Reasignación a proyecto macro (Hyperscale) vía Exceltic.",
    },
    {
      dates: "2024-08 a 2024-09",
      duration: "2 meses",
      company: "Germania",
      sector: "Subcontratista MEP",
      role: "Modelador BIM MEP / CAD",
      location: "Madrid, España",
      project: "Residencial / Transporte (Multi-proyecto)",
      summary: "• Producción de planos de taller de instalaciones y mediciones manuales preventivas.",
      reasonForLeaving: "Oferta corporativa internacional (OTAN).",
    },
    {
      dates: "2024-06 a 2024-08",
      duration: "3 meses",
      company: "EAG (GHESA)",
      sector: "Consultoría de Ingeniería",
      role: "Arquitecto BIM",
      location: "España",
      project: "Camp Nou FC Barcelona (~300.000m² | ~€1.3B)",
      summary: "• Liderazgo del equipo de modelado on-site para arquitectura bajo modelo federado gigante.\n• Implementación de flujos CDE e ISO 19650 en proyecto deportivo de máxima visibilidad europea.",
      reasonForLeaving: "Reasignación estratégica dentro de la consultora matriz.",
    },
    {
      dates: "2023-06 a 2024-08",
      duration: "14 meses",
      company: "Plenum Ingenieros",
      sector: "Consultoría BIM / Outsourcing",
      role: "BIM Manager / Operations Manager",
      location: "España",
      project: "Fehmarnbelt Tunnel (~€7.4B) | P. Marqués Salamanca | Fac. Matemáticas UCM",
      summary: "• Dirección del departamento BIM gestionando un equipo de 16 profesionales con metodologías PMBOK y Agile.\n• Coordinación Open BIM (IFC) de 22 segmentos del túnel Fehmarnbelt, resolviendo problemas de interoperabilidad complejos.\n• Gestión del ciclo de vida ISO 19650 (BEP, CDE, LoIN) y sesiones ICE para resolución de clashes críticos.",
      reasonForLeaving: "Paralización temporal del macroproyecto (Túnel); transición tras consolidar el departamento.",
    },
    {
      dates: "2022-07 a 2023-06",
      duration: "11 meses",
      company: "Plenum Ingenieros",
      sector: "Consultoría BIM",
      role: "Arquitecto BIM / Especialista MEP",
      location: "España",
      project: "IDOM (TMT Telescope ~€1.7B, Hospitales) | Hospital Dakar (~€135M) | ARUP",
      summary: "• Lead Modelator Arquitectura & MEP en simultáneo para Hospitales, Proyectos Científicos y Educación.\n• Promovido a BIM Manager por capacidad nativa para estabilizar flujos de trabajo caóticos y liderar al equipo técnico.\n• Creación de librerías Revit estandarizadas y assets automatizados para el departamento.",
      reasonForLeaving: "Ascenso a BIM Manager departamental.",
    },
    {
      dates: "2020-07 a 2021-07",
      duration: "1 año",
      company: "Ferrocerámica Valcro",
      sector: "Constructora Promotora",
      role: "Arquitecto BIM",
      location: "Venezuela",
      project: "Isla Multiespacio (~90.000m²) | Cameva Retail",
      summary: "• Digitalización del diseño arquitectónico en entorno BIM. Producción de planos ejecutivos, renders y supervisión a pie de obra.",
      reasonForLeaving: "Expatriación internacional para especialización PMP.",
    },
  ],
  earlierExperience: [
    { role: "Director de Proyectos Arquitectónicos", company: "AESTUDIO", year: "2022" },
    { role: "Arquitecto Freelance", company: "Freelance", year: "2021" },
    { role: "Editor (Español-Inglés)", company: "XiaomiToday", year: "2017–2018" },
    { role: "Arquitecto en Prácticas", company: "ARCOS 5", year: "2017" },
  ],
  technicalSkills: [
    { category: "BIM y Coordinación", skills: ["Revit (MEP, Arquitectura, Estructura) – Experto", "Navisworks (Detección de Interferencias)", "AutoCAD 2D/3D"] },
    { category: "Automatización y Programación", skills: ["Dynamo", "Python", "Currículo de Ciencias de la Computación C 42 Madrid (En curso)"] },
    { category: "Captura de Realidad", skills: ["Flujos de trabajo Scan-to-BIM", "Integración de Nubes de Puntos (LIDAR)"] },
    { category: "Gestión de Proyectos y Costes", skills: ["Microsoft Project", "CYPE", "Presto"] },
    { category: "Visualización", skills: ["3Ds Max", "V-Ray", "Lumion", "Twinmotion", "D5"] },
    { category: "Otros", skills: ["Entornos CDE (ACC)", "Gestión de Infraestructura de IT", "Consultoría Técnica"] },
  ],
  education: [
    { degree: "Máster en Dirección Integrada de Proyectos (PMP)", institution: "Universidad de A Coruña – España" },
    { degree: "Grado en Arquitectura", institution: "I.U.P.S.M. Maracay – Venezuela (HOMOLOGACIÓN ANECA ESPAÑA)" },
    { degree: "Ciencias de la Computación (En curso)", institution: "42 Madrid - España" },
  ],
  awards: [
    { title: "Premio a la Excelencia por Logros en el Extranjero", issuer: "Xunta de Galicia (España)", year: "2022", description: "Reconocimiento oficial otorgado por el desempeño académico y profesional en el extranjero" },
  ],
  certifications: [
    "Experto en Autodesk Revit Architecture",
    "Coordinador de Autodesk Revit MEP",
    "Gestión de Proyectos BIM – Fundación Confemetal",
  ],
  languages: [
    { language: "Español", level: "Nativo" },
    { language: "Inglés", level: "Bilingüe" },
  ],
};
