import { CVData } from "./types";

export const cvData: CVData = {
  name: "ARMANDO ANTONIO GONZÁLEZ TAPIADOR",
  title: "BIM Manager / Coordinador y Director de Proyectos PMP",
  contact: {
    location: "Alicante, España",
    phone: "+34 666 77 61 78",
    email: "arq.nate@gmail.com",
    linkedin: "linkedin.com/in/armando-gonzalez-tapiador",
    photo: "https://media.licdn.com/dms/image/v2/D4D03AQEW8hzfDwtP8A/profile-displayphoto-shrink_800_800/B4DZSzL4cLHkAc-/0/1738173025110?e=1775692800&v=beta&t=GzVQ_npAg3v4AuVE6Yr-8slyTcuNGm_Hratov_YpwCY",
  },
  summary: "• Dirección de operaciones BIM a escala departamental (PMBOK / ISO 21502 / ISO 19650).\n• Gestión concurrente de megaproyectos internacionales (Data Centers, Infraestructura, Salud) valorados en >€10.000M.\n• Liderazgo técnico y adquisición de talento para equipos multidisciplinarios (hasta 16 miembros) en entornos CDE.\n• Creación de herramientas (Python/Dynamo) para QA federado y automatización de procesos.",
  experience: [
    {
      dates: "2025-08 a la actualidad",
      duration: "En curso",
      company: "Germania de Instalaciones",
      sector: "Subcontratista MEP",
      role: "Coordinador BIM MEP",
      location: "Alicante, España",
      project: "Ampliación del Hospital de Orihuela (~45.000m² | ~€70M)",
      summary: "• Único recurso BIM inter-empresa (Valnu → Rover → Germania) para el alcance HVAC MEP en ampliación sanitaria crítica.\n• Coordinación end-to-end: modelado de sistemas mecánicos en cubierta, cuantificación por fases y verificación in situ.\n• Establecimiento de estándares BIM funcionales mínimos (LoIN/BEP) adaptados a necesidades operativas reales.\n• Gestión de flujos de trabajo de modelos federados para adquisición basada en datos y validación de suministro.",
      reasonForLeaving: "N/A - Puesto actual",
    },
    {
      dates: "2025-05 a 2025-08",
      duration: "4 meses",
      company: "NTI Spain",
      sector: "Consultoría BIM / Autodesk Platinum",
      role: "Consultor BIM AEC",
      location: "Madrid, España",
      project: "Diversos perfiles Tier 1 (AEC)",
      summary: "• Diagnóstico de madurez BIM y flujos de trabajo de clientes Tier 1 para estrategias de adopción de software.\n• Posicionamiento e integración técnica de Environment for Revit, NTI for Revit y Realtime LCA a través de Speckle.\n• Preparación del sector para la refundición de la EPBD (UE 2024/1275) e informes WLC de Level(s).\n• Implementación de CDE y norma ISO 19650 para elevar los estándares de entrega multidisciplinaria interna.",
      reasonForLeaving: "Acepté oferta para proyecto hospitalario de gran escala (Germania).",
    },
    {
      dates: "2024-11 a 2025-05",
      duration: "7 meses",
      company: "Exceltic",
      sector: "Consultoría de Ingeniería",
      role: "Arquitecto BIM / Especialista MEP",
      location: "España",
      project: "Centros de Datos Hyperscale (~€6-10B) & Infraestructura Defensa OTAN (~€0.8B)",
      summary: "• Diseño técnico y coordinación espacial MEP (LOD 300-350) bilingüe para Centros de Datos e Infraestructura de Defensa.\n• Manejo de proyectos de misión crítica protegidos por acuerdos de confidencialidad (NDA).\n• Producción bajo marcos estrictos de consultoría AECOM y estándares del Cuerpo de Ingenieros del Ejército (USACE).\n• Seguimiento riguroso de entregables escalonados por fases de hito (30/60/90/100%).",
      reasonForLeaving: "Finalización de fase; reorientación a consultoría técnica corporativa.",
    },
    {
      dates: "2024-09 a 2024-10",
      duration: "2 meses",
      company: "ADYD Group",
      sector: "Consultoría de Ingeniería",
      role: "Arquitecto BIM",
      location: "España / Bélgica",
      project: "Defensa OTAN (~250.000m² | ~€0.8B)",
      summary: "• Diseño y coordinación BIM MEP de despliegue rápido para instalaciones de defensa de la OTAN en Bélgica.\n• Operación bajo protocolos internacionales AECOM/USACE en un entorno totalmente bilingüe.\n• Gestión analítica de entregas por fases para asegurar compromisos a largo plazo con el cliente institucional.",
      reasonForLeaving: "Reasignación a proyecto macro (Hyperscale) vía Exceltic.",
    },
    {
      dates: "2024-08 a 2024-09",
      duration: "2 meses",
      company: "Germania",
      sector: "Subcontratista MEP",
      role: "Modelador BIM MEP / CAD",
      location: "Madrid, España",
      project: "Residencial / Transporte (Multi-proyecto)",
      summary: "• Apoyo técnico a flujos de trabajo de pre-construcción en proyectos residenciales, industriales y transporte.\n• Preparación de distribuciones espaciales MEP en CAD y generación de planos de producción de obra.\n• Extracción de mediciones manuales ágiles para gestión y control en múltiples proyectos concurrentes.",
      reasonForLeaving: "Oferta corporativa internacional (OTAN).",
    },
    {
      dates: "2024-06 a 2024-08",
      duration: "3 meses",
      company: "EAG (GHESA)",
      sector: "Consultoría de Ingeniería",
      role: "Arquitecto BIM",
      location: "España",
      project: "Camp Nou FC Barcelona (~300.000m² | ~€1.3B)",
      summary: "• Liderazgo directivo del equipo de modelado in situ de Plenum para la producción BIM arquitectónica del proyecto estadio.\n• Control de calidad estricto de entregables dentro de modelo federado de altísima densidad y complejidad geométrica.\n• Gobernanza operacional regida rigurosamente por flujos de trabajo ISO 19650 y esquemas CDE integrados.\n• Prestación de soporte técnico remoto ininterrumpido para estabilizar operaciones tras el despliegue de fases.",
      reasonForLeaving: "Reasignación estratégica dentro de la consultora matriz.",
    },
    {
      dates: "2023-06 a 2024-08",
      duration: "14 meses",
      company: "Plenum Ingenieros",
      sector: "Consultoría BIM / Outsourcing",
      role: "BIM Manager / Operations Manager",
      location: "España",
      project: "Fehmarnbelt Tunnel (~€7.4B) | P. Marqués Salamanca | Fac. Matemáticas UCM",
      summary: "• Dirección de operaciones BIM (PMBOK / ISO 21502 / Agile) gestionando 4 megaproyectos internacionales (>€7.000M).\n• Liderazgo del ciclo de vida ISO 19650: re-implementación de BEPs, definición rigurosa de LoIN y administración en CDE.\n• Adquisición, gestión y capacitación de talento técnico para equipo multidisciplinar de 16 profesionales (Arq/Est/MEP).\n• Coordinación Open BIM de 22 segmentos del túnel sumergido más largo del mundo (Fehmarnbelt) bajo metodología Kanban.\n• Implementación de QA sistemático, defensa de modelos federados en sesiones ICE y resolución de interoperabilidad.",
      reasonForLeaving: "Paralización temporal del macroproyecto (Túnel); transición tras consolidar el departamento.",
    },
    {
      dates: "2022-07 a 2023-06",
      duration: "11 meses",
      company: "Plenum Ingenieros",
      sector: "Consultoría BIM",
      role: "Arquitecto BIM / Especialista MEP",
      location: "España",
      project: "IDOM (TMT Telescope ~€1.7B, Hospitales) | Hospital Dakar (~€135M) | ARUP",
      summary: "• Recurso técnico núcleo en volumen extremo de proyectos multidisciplinares (Salud, Científico, Transporte) bajo hitos implacables.\n• Absorción proactiva de la gestión BIM departamental en cuellos de botella y coordinación on-site del compromiso Camp Nou.\n• Liderazgo en especificación técnica de infraestructura IT y despliegue de servidores para prevenir crash de datos masivos.\n• Desarrollo de bibliotecas estándar, assets automatizados y flujos de scripting (Python/Dynamo) como núcleo del departamento.\n• Asesoría PM/PMP proactiva a la dirección de la empresa provocando un ascenso unánime a BIM Manager.",
      reasonForLeaving: "Ascenso a BIM Manager departamental.",
    },
    {
      dates: "2020-07 a 2021-07",
      duration: "1 año",
      company: "Ferrocerámica Valcro",
      sector: "Constructora Promotora",
      role: "Arquitecto BIM",
      location: "Venezuela",
      project: "Isla Multiespacio (~90.000m²) | Cameva Retail",
      summary: "• Entrega integral de documentación BIM arquitectónica y estructural para proyectos de uso mixto de alta escala.\n• Producción de entregables completos: planos de obra, secciones constructivas, renderizado y visualizaciones de venta.\n• Supervisión directa a pie de obra garantizando alineación geométrica y técnica entre el modelo y la construcción física.\n• Coordinación multiplataforma y multidisciplinar (ArchiCAD/Revit) estableciendo conocimientos fundamentales en IFC.",
      reasonForLeaving: "Expatriación internacional para especialización PMP.",
    },
  ],
  earlierExperience: [
    { role: "Director de Proyectos Arquitectónicos", company: "AESTUDIO", year: "2022" },
    { role: "Arquitecto Freelance", company: "Freelance", year: "2021" },
    { role: "Editor (Español-Inglés)", company: "XiaomiToday", year: "2017–2018" },
    { role: "Arquitecto en Prácticas", company: "ARCOS 5", year: "2017" },
  ],
  technicalSkills: [
    { category: "BIM y Coordinación", skills: ["Revit (MEP, Arquitectura, Estructura) – Experto", "Navisworks (Detección de Interferencias)", "AutoCAD 2D/3D"] },
    { category: "Automatización y Programación", skills: ["Dynamo", "Python", "Currículo de Ciencias de la Computación C 42 Madrid (En curso)"] },
    { category: "Captura de Realidad", skills: ["Flujos de trabajo Scan-to-BIM", "Integración de Nubes de Puntos (LIDAR)"] },
    { category: "Gestión de Proyectos y Costes", skills: ["Microsoft Project", "CYPE", "Presto"] },
    { category: "Visualización", skills: ["3Ds Max", "V-Ray", "Lumion", "Twinmotion", "D5"] },
    { category: "Otros", skills: ["Entornos CDE (ACC)", "Gestión de Infraestructura de IT", "Consultoría Técnica"] },
  ],
  education: [
    { degree: "Máster en Dirección Integrada de Proyectos (PMP)", institution: "Universidad de A Coruña – España" },
    { degree: "Grado en Arquitectura", institution: "I.U.P.S.M. Maracay – Venezuela (HOMOLOGACIÓN ANECA ESPAÑA)" },
    { degree: "Ciencias de la Computación (En curso)", institution: "42 Madrid - España" },
  ],
  awards: [
    { title: "Premio a la Excelencia por Logros en el Extranjero", issuer: "Xunta de Galicia (España)", year: "2022", description: "Reconocimiento oficial otorgado por el desempeño académico y profesional en el extranjero" },
  ],
  certifications: [
    "Experto en Autodesk Revit Architecture",
    "Coordinador de Autodesk Revit MEP",
    "Gestión de Proyectos BIM – Fundación Confemetal",
  ],
  languages: [
    { language: "Español", level: "Nativo" },
    { language: "Inglés", level: "Bilingüe" },
  ],
};
