import { PortfolioProject } from "./types";

// ─── SPANISH ────────────────────────────────────────────────────────────────
export const portfolioDataEs: PortfolioProject[] = [
  // ── Fehmarnbelt ──────────────────────────────────────────────────────────
  {
    id: "fehmarnbelt",
    title: "Enlace Fijo de Fehmarnbelt",
    category: "Infraestructura",
    location: "Dinamarca – Alemania",
    area: "18 km",
    value: "~€7.400 M",
    description: "Coordinación Open BIM de 22 segmentos del túnel sumergido de carretera y ferrocarril más largo del mundo. Programación basada en Kanban con reporte directo a los BIM Managers senior de IDOM.",
    methodology: ["ISO 19650", "Open BIM", "Kanban"],
    techStack: ["Revit", "Navisworks", "BIMcollab"],
  },
  // ── Camp Nou ─────────────────────────────────────────────────────────────
  {
    id: "camp-nou",
    title: "Remodelación Spotify Camp Nou",
    category: "Deportes",
    location: "Barcelona, España",
    area: "~300.000 m²",
    value: "~€1.300 M",
    description: "Dirección del equipo de modelado in situ de Plenum en GHESA. Producción BIM arquitectónica dentro de un modelo federado de alta densidad gobernado por flujos ISO 19650 y CDE.",
    methodology: ["ISO 19650", "CDE", "Modelo Federado"],
    techStack: ["Revit", "Dynamo", "ACC"],
  },
  // ── Data Centers ─────────────────────────────────────────────────────────
  {
    id: "data-centers",
    title: "Centros de Datos a Hiperescala",
    category: "Misión Crítica",
    location: "España",
    area: "~20.000 m² IT/instalación",
    value: "~€6-10B (Programa)",
    description: "Producción de paquetes de diseño técnico MEP y coordinación espacial (LOD 300-350) para Microsoft y Amazon bajo marcos de AECOM. Control de hitos por fases (30/60/90/100%).",
    methodology: ["LOD 300-350", "Entregables Escalonados"],
    techStack: ["Revit MEP", "Navisworks"],
  },
  // ── NATO Defense ─────────────────────────────────────────────────────────
  {
    id: "nato-defense",
    title: "Infraestructura de Defensa OTAN",
    category: "Defensa",
    location: "Bélgica (vía AECOM)",
    area: "~250.000 m²",
    value: "~€800 M",
    description: "Diseño y coordinación BIM bajo protocolos AECOM/USACE. Gestión de entregas escalonadas en entorno bilingüe (inglés/español).",
    methodology: ["USACE", "Entregables Escalonados"],
    techStack: ["Revit", "Navisworks"],
  },
  // ── Hospital Orihuela ────────────────────────────────────────────────────
  {
    id: "hospital-orihuela",
    title: "Ampliación Hospital de Orihuela",
    category: "Salud",
    location: "Alicante, España",
    area: "~45.000 m²",
    value: "~€70 M",
    description: "Único recurso BIM para el alcance de climatización MEP de Germania: modelado de sistemas mecánicos en cubierta, cuantificación por fases (construido vs. pendiente) y verificación de obra in situ.",
    methodology: ["LoIN/BEP", "Modelos Federados", "Verificación As-Built"],
    techStack: ["Revit MEP", "Navisworks"],
  },
  // ── Giant Magellan Telescope ─────────────────────────────────────────────
  {
    id: "magellan-telescope",
    title: "Telescopio Gigante de Magallanes",
    category: "Científico",
    location: "Chile (vía IDOM)",
    value: "~€1.700 M",
    description: "Coordinación MEP y arquitectónica bajo plazos implacables para una de las infraestructuras científicas más avanzadas del mundo.",
    methodology: ["Clash Detection"],
    techStack: ["Revit", "Navisworks"],
  },
  // ── Hospital Donostia ────────────────────────────────────────────────────
  {
    id: "hospital-donostia",
    title: "Hospital Universitario Donostia",
    category: "Salud",
    location: "San Sebastián, España",
    description: "Coordinación MEP y arquitectónica dentro de un volumen extremo de proyectos sanitarios concurrentes gestionados por IDOM.",
    methodology: ["Ingeniería Concurrente"],
    techStack: ["Revit", "Navisworks"],
  },
  // ── Hospital Basurto ─────────────────────────────────────────────────────
  {
    id: "hospital-basurto",
    title: "Hospital de Basurto",
    category: "Salud",
    location: "Bilbao, España",
    description: "Coordinación MEP y arquitectónica. Resolución de cuellos de botella de datos en modelos concurrentes a gran escala.",
    methodology: ["Ingeniería Concurrente"],
    techStack: ["Revit", "Navisworks", "Dynamo"],
  },
  // ── Hospital ACH Dakar ───────────────────────────────────────────────────
  {
    id: "hospital-dakar",
    title: "Hospital ACH Dakar",
    category: "Salud Internacional",
    location: "Dakar, Senegal",
    area: "~40.000 m²",
    value: "~€135 M",
    description: "Coordinación arquitectónica y desarrollo de bibliotecas BIM estandarizadas para componentes sanitarios.",
    methodology: ["Estandarización Paramétrica"],
    techStack: ["Revit"],
  },
  // ── Palacio Marqués de Salamanca ─────────────────────────────────────────
  {
    id: "heritage-salamanca",
    title: "Palacio Marqués de Salamanca",
    category: "Patrimonio",
    location: "Madrid, España",
    area: "~25.000 m²",
    value: "~€50 M",
    description: "Sede patrimonial histórica. Integración de instalaciones MEP bajo restricciones de conservación arquitectónica.",
    methodology: ["HBIM"],
    techStack: ["Revit"],
  },
  // ── Facultad Matemáticas UCM ─────────────────────────────────────────────
  {
    id: "ucm-math",
    title: "Facultad de Matemáticas UCM",
    category: "Educación",
    location: "Madrid, España",
    area: "~15.000 m²",
    description: "Gestión BIM dentro del contexto de 4 megaproyectos internacionales concurrentes dirigidos a nivel departamental.",
    methodology: ["ISO 19650", "PMBOK"],
    techStack: ["Revit"],
  },
  // ── Hoteles ARUP ─────────────────────────────────────────────────────────
  {
    id: "arup-hotels",
    title: "Hoteles ARUP",
    category: "Hostelería",
    location: "España",
    area: "~10.000 m²",
    value: "~€40 M",
    description: "Coordinación MEP y arquitectónica para equipamientos hoteleros bajo el marco de trabajo de ARUP.",
    methodology: ["Coordinación Multidisciplinar"],
    techStack: ["Revit"],
  },
  // ── Isla Multiespacio ────────────────────────────────────────────────────
  {
    id: "isla-multiespacio",
    title: "Torre Isla Multiespacio",
    category: "Uso Mixto / Gran Altura",
    location: "Venezuela",
    area: "~90.000 m²",
    value: "~€150 M",
    description: "Documentación BIM arquitectónica y estructural completa. Supervisión periódica de obra. Coordinación multiplataforma con equipos de ArchiCAD vía IFC/Open BIM.",
    methodology: ["Open BIM", "IFC", "Supervisión de Obra"],
    techStack: ["Revit", "ArchiCAD", "AutoCAD", "V-Ray"],
  },
  // ── Cadena Retail Cameva ─────────────────────────────────────────────────
  {
    id: "cameva-retail",
    title: "Cadena Comercial Cameva",
    category: "Retail",
    location: "Venezuela",
    area: "~20.000 m²",
    value: "~€30 M (agregado)",
    description: "Producción de planos, secciones, detalles constructivos, renders, visualizaciones y cuantificación de materiales para múltiples locales.",
    methodology: ["Documentación Constructiva"],
    techStack: ["Revit", "AutoCAD", "V-Ray"],
  },
  // ── NTI Consultoría ──────────────────────────────────────────────────────
  {
    id: "nti-consulting",
    title: "Consultoría BIM AEC (NTI Spain)",
    category: "Consultoría",
    location: "Madrid, España",
    description: "Evaluación de flujos BIM y madurez digital de clientes Tier-1 como Autodesk Platinum Partner. Formación y posicionamiento de herramientas (Environment for Revit, Realtime LCA vía Speckle). Preparación para la EPBD (UE 2024/1275).",
    methodology: ["ISO 19650", "CDE", "Formación"],
    techStack: ["Revit", "Speckle", "Environment for Revit"],
  },
];

// ─── ENGLISH ────────────────────────────────────────────────────────────────
export const portfolioDataEn: PortfolioProject[] = [
  {
    id: "fehmarnbelt",
    title: "Fehmarnbelt Fixed Link",
    category: "Infrastructure",
    location: "Denmark – Germany",
    area: "18 km",
    value: "~€7.4B",
    description: "Open BIM coordination for 22 segments of the world's longest immersed road and rail tunnel. Kanban-based scheduling with direct reporting to IDOM's senior BIM Managers.",
    methodology: ["ISO 19650", "Open BIM", "Kanban"],
    techStack: ["Revit", "Navisworks", "BIMcollab"],
  },
  {
    id: "camp-nou",
    title: "Spotify Camp Nou Remodeling",
    category: "Sports",
    location: "Barcelona, Spain",
    area: "~300,000 sqm",
    value: "~€1.3B",
    description: "Directed Plenum's on-site modeling team at GHESA. Architectural BIM production within a high-density federated model governed by ISO 19650 workflows and CDE.",
    methodology: ["ISO 19650", "CDE", "Federated Model"],
    techStack: ["Revit", "Dynamo", "ACC"],
  },
  {
    id: "data-centers",
    title: "Hyperscale Data Centers",
    category: "Mission Critical",
    location: "Spain",
    area: "~20,000 sqm IT/facility",
    value: "~€6-10B (Program)",
    description: "MEP technical design packages and spatial coordination (LOD 300-350) for Microsoft and Amazon under AECOM frameworks. Phased milestone control (30/60/90/100%).",
    methodology: ["LOD 300-350", "Phased Deliverables"],
    techStack: ["Revit MEP", "Navisworks"],
  },
  {
    id: "nato-defense",
    title: "NATO Defense Infrastructure",
    category: "Defense",
    location: "Belgium (via AECOM)",
    area: "~250,000 sqm",
    value: "~€800M",
    description: "BIM design and coordination under AECOM/USACE protocols. Managed staggered deliverables in a bilingual environment (English/Spanish).",
    methodology: ["USACE", "Phased Deliverables"],
    techStack: ["Revit", "Navisworks"],
  },
  {
    id: "hospital-orihuela",
    title: "Orihuela Hospital Expansion",
    category: "Healthcare",
    location: "Alicante, Spain",
    area: "~45,000 sqm",
    value: "~€70M",
    description: "Sole BIM resource for Germania's MEP HVAC scope: rooftop mechanical systems modeling, phased quantification (as-built vs. pending), and on-site verification.",
    methodology: ["LoIN/BEP", "Federated Workflows", "As-Built Verification"],
    techStack: ["Revit MEP", "Navisworks"],
  },
  {
    id: "magellan-telescope",
    title: "Giant Magellan Telescope",
    category: "Scientific",
    location: "Chile (via IDOM)",
    value: "~€1.7B",
    description: "MEP and architectural coordination under relentless deadlines for one of the world's most advanced scientific megastructures.",
    methodology: ["Clash Detection"],
    techStack: ["Revit", "Navisworks"],
  },
  {
    id: "hospital-donostia",
    title: "Donostia University Hospital",
    category: "Healthcare",
    location: "San Sebastián, Spain",
    description: "MEP and architectural coordination within an extreme volume of concurrent healthcare projects managed by IDOM.",
    methodology: ["Concurrent Engineering"],
    techStack: ["Revit", "Navisworks"],
  },
  {
    id: "hospital-basurto",
    title: "Basurto Hospital",
    category: "Healthcare",
    location: "Bilbao, Spain",
    description: "MEP and architectural coordination. Resolved data bottlenecks in large-scale concurrent models.",
    methodology: ["Concurrent Engineering"],
    techStack: ["Revit", "Navisworks", "Dynamo"],
  },
  {
    id: "hospital-dakar",
    title: "ACH Dakar Hospital",
    category: "International Healthcare",
    location: "Dakar, Senegal",
    area: "~40,000 sqm",
    value: "~€135M",
    description: "Architectural coordination and development of standardized BIM libraries for healthcare components.",
    methodology: ["Parametric Standardization"],
    techStack: ["Revit"],
  },
  {
    id: "heritage-salamanca",
    title: "Marqués de Salamanca Palace",
    category: "Heritage",
    location: "Madrid, Spain",
    area: "~25,000 sqm",
    value: "~€50M",
    description: "Historic heritage headquarters. MEP integration under strict architectural preservation constraints.",
    methodology: ["HBIM"],
    techStack: ["Revit"],
  },
  {
    id: "ucm-math",
    title: "UCM Mathematics Faculty",
    category: "Education",
    location: "Madrid, Spain",
    area: "~15,000 sqm",
    description: "BIM management within the context of 4 concurrent international megaprojects directed at department level.",
    methodology: ["ISO 19650", "PMBOK"],
    techStack: ["Revit"],
  },
  {
    id: "arup-hotels",
    title: "ARUP Hotels",
    category: "Hospitality",
    location: "Spain",
    area: "~10,000 sqm",
    value: "~€40M",
    description: "MEP and architectural coordination for hotel facilities under ARUP's delivery framework.",
    methodology: ["Multidisciplinary Coordination"],
    techStack: ["Revit"],
  },
  {
    id: "isla-multiespacio",
    title: "Isla Multiespacio Tower",
    category: "Mixed-Use / High-Rise",
    location: "Venezuela",
    area: "~90,000 sqm",
    value: "~€150M",
    description: "Complete architectural and structural BIM documentation. Periodic on-site construction supervision. Cross-platform coordination with ArchiCAD teams via IFC/Open BIM.",
    methodology: ["Open BIM", "IFC", "Site Supervision"],
    techStack: ["Revit", "ArchiCAD", "AutoCAD", "V-Ray"],
  },
  {
    id: "cameva-retail",
    title: "Cameva Retail Chain",
    category: "Retail",
    location: "Venezuela",
    area: "~20,000 sqm",
    value: "~€30M (aggregate)",
    description: "Production of drawings, sections, construction details, renderings, visualizations, and material take-offs across multiple locations.",
    methodology: ["Construction Documentation"],
    techStack: ["Revit", "AutoCAD", "V-Ray"],
  },
  {
    id: "nti-consulting",
    title: "AEC BIM Consulting (NTI Spain)",
    category: "Consulting",
    location: "Madrid, Spain",
    description: "BIM workflow and digital maturity assessment for Tier-1 clients as Autodesk Platinum Partner. Training and tool positioning (Environment for Revit, Realtime LCA via Speckle). EPBD (EU 2024/1275) readiness.",
    methodology: ["ISO 19650", "CDE", "Training"],
    techStack: ["Revit", "Speckle", "Environment for Revit"],
  },
];
