import { PortfolioProject } from "./types";

export const portfolioDataEs: PortfolioProject[] = [
  {
    id: "fehmarnbelt",
    title: "Túnel de Fehmarnbelt (Enlace Fijo)",
    category: "Infraestructura Pesada",
    location: "Dinamarca - Alemania",
    area: "18 km de longitud",
    value: "€7.400 M",
    description: "Dirección de operaciones BIM para el túnel sumergido más largo del mundo. Coordinación Open BIM de 22 segmentos estructurales críticos informando directamente a los directivos de IDOM.",
    methodology: ["ISO 19650", "CDE Management", "Kanban / Agile"],
    techStack: ["Revit", "Navisworks", "Synchro 4D", "BIMcollab"],
    imageUrl: "https://images.unsplash.com/photo-1545139239-e817af750cd5?q=80&w=2070&auto=format&fit=crop"
  },
  {
    id: "data-centers",
    title: "Centros de Datos Hyperscale",
    category: "Misión Crítica / IT",
    location: "España / Europa",
    area: "20.000 m² IT por clúster",
    value: "+€6.000 M (Programa Regional)",
    description: "Producción de paquetes de diseño técnico MEP y coordinación espacial (LOD 300-350) para nubes hiperescala de Microsoft y Amazon bajo frameworks de AECOM y estrictos protocolos de confidencialidad (NDA).",
    methodology: ["MEP Coordination", "Technical Design", "Security Protocols"],
    techStack: ["Revit MEP", "Navisworks", "Python (Scripting)"],
    imageUrl: "https://images.unsplash.com/photo-1558494949-ef010958384e?q=80&w=2000&auto=format&fit=crop"
  },
  {
    id: "camp-nou",
    title: "Spotify Camp Nou",
    category: "Deportes / Estadios",
    location: "Barcelona, España",
    area: "300.000 m²",
    value: "€1.300 M",
    description: "Liderazgo del equipo de modelado arquitectónico in situ en GHESA. Gestión de modelos federados de alta densidad para la principal estructura de hormigón en la remodelación del estadio más grande de Europa.",
    methodology: ["VDC", "Clash Detection", "ICE Sessions"],
    techStack: ["Revit", "Dynamo", "ACC"],
    imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=2070&auto=format&fit=crop"
  },
  {
    id: "nato-defense",
    title: "Infraestructura de Defensa OTAN",
    category: "Milicia / Defensa",
    location: "Bélgica",
    area: "250.000 m²",
    value: "€800 M",
    description: "Diseño BIM de despliegue rápido y coordinación espacial bajo protocolos USACE (Cuerpo de Ingenieros del Ejército de EE. UU.). Control riguroso de redacciones y entregables escalonados (30/60/90/100%).",
    methodology: ["USACE Standards", "Phased Deliverables", "Secure BIM"],
    techStack: ["Revit", "Navisworks", "Plataformas Seguras CDE"],
    imageUrl: "https://images.unsplash.com/photo-1584462198614-046129841029?q=80&w=2070&auto=format&fit=crop"
  },
  {
    id: "magellan-telescope",
    title: "Telescopio Gigante de Magallanes (GMT)",
    category: "Científico / Ingeniería",
    location: "Desierto de Atacama, Chile (via IDOM)",
    area: "No divulgado publicamente",
    value: "€1.700 M",
    description: "Coordinación de extrema precisión espacial MEP/Arquitectura resolviendo severas restricciones para albergar equipos ópticos de escala masiva. Desarrollo bajo plazos de tiempo implacables.",
    methodology: ["High-Precision VDC", "Clash Resolution System"],
    techStack: ["Revit", "Navisworks", "Gestión de Servidores IT"],
    imageUrl: "https://images.unsplash.com/photo-1549495689-f55dbbb02a3a?q=80&w=2070&auto=format&fit=crop"
  },
  {
    id: "hospital-orihuela",
    title: "Ampliación Hospital de Orihuela",
    category: "Sanidad / Salud",
    location: "Alicante, España",
    area: "45.000 m²",
    value: "€70 M",
    description: "Único recurso BIM de Germania para el total del alcance HVAC/Fluidos. Entregables incluyendo modelado de precisión de equipos de cubierta y verificación As-Built de las obras mecánicas construidas.",
    methodology: ["LoIN / BEP", "Federated Workflows", "As-Built Verification"],
    techStack: ["Revit MEP", "Navisworks", "Procesos de Compra Constructivos"],
    imageUrl: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=2053&auto=format&fit=crop"
  },
  {
    id: "hospital-donostia",
    title: "Hospital Universitario Donostia",
    category: "Sanidad / Salud",
    location: "San Sebastián, España",
    area: "Gran Escala (Aprox 200.000 m² Faseados)",
    value: "+€250 M",
    description: "Coordinación arquitectónica y revisión minuciosa de sistemas pasivos. Proyecto sujeto a estrictas normativas del Sistema Público Vasco de Salud (Osakidetza).",
    methodology: ["ISO 19650", "Concurrent Engineering", "Normativa Sanitaria"],
    techStack: ["Revit Architecture", "Navisworks", "BIM 360 / ACC"],
    imageUrl: "https://images.unsplash.com/photo-1538108149393-fbbd81895907?q=80&w=2000&auto=format&fit=crop"
  },
  {
    id: "hospital-basurto",
    title: "Hospital de Basurto",
    category: "Sanidad / Salud",
    location: "Bilbao, España",
    area: "Gran Escala",
    value: "Presupuesto No Divulgado",
    description: "Proyecto de modernización continua requiriendo coordinación MEP y arquitectónica. Resolución de cuellos de botella mediante auditorías de modelos gigantes divididos por clusters.",
    methodology: ["Data Bottleneck Relief", "Auditoría BIM", "QA Governance"],
    techStack: ["Revit", "Navisworks Manage", "Dynamo Graphs"],
    imageUrl: "https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=2074&auto=format&fit=crop"
  },
  {
    id: "hospital-dakar",
    title: "Centro Hospitalario ACH Dakar",
    category: "Sanidad Internacional",
    location: "Dakar, Senegal",
    area: "40.000 m²",
    value: "€135 M",
    description: "Gestión de modelos complejos arquitectónicos desde fase cero hasta documentación constructiva para África Occidental. Implementación de una librería estandarizada masiva para componentes de salud.",
    methodology: ["Parametric Standardization", "International Delivery"],
    techStack: ["Revit", "Librerías Creadas (Families)"],
    imageUrl: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?q=80&w=2073&auto=format&fit=crop"
  },
  {
    id: "heritage-salamanca",
    title: "Palacio Marqués de Salamanca HQ",
    category: "Patrimonial / Corporativo",
    location: "Madrid, España",
    area: "25.000 m²",
    value: "€50 M",
    description: "Integración de instalaciones súper-eficientes en una sede patrimonial histórica. Equilibrando las rutas severas MEP con imposiciones estéticas absolutas impuestas por patrimonio arquitectónico.",
    methodology: ["Heritage BIM (HBIM)", "Scan-to-BIM", "Point Cloud Intel"],
    techStack: ["Revit", "ReCap", "LiDAR Data"],
    imageUrl: "https://images.unsplash.com/photo-1621614050901-71fb264f33b1?q=80&w=2012&auto=format&fit=crop"
  },
  {
    id: "isla-multiespacio",
    title: "Rascacielos Isla Multiespacio",
    category: "Uso Mixto / High-Rise",
    location: "Valencia, Venezuela",
    area: "90.000 m²",
    value: "€150 M",
    description: "Producción completa estructural y arquitectónica BIM guiando a la constructora. Superé las fricciones de interoperabilidad entre equipos separados trabajando en Revit y ArchiCAD vía OpenBIM.",
    methodology: ["Open BIM", "IFC Interoperability", "Supervisión de Obra"],
    techStack: ["Revit", "ArchiCAD", "V-Ray", "AutoCAD"],
    imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=2070&auto=format&fit=crop"
  },
  {
    id: "automation-n8n",
    title: "Sistemas Rígidos de Automatización (n8n/Make)",
    category: "Ingeniería de Automatización BIM",
    location: "Desarrollo Cloud",
    area: "Software Internal",
    value: "Integración",
    description: "Creación de flujos de trabajo API que interactúan con modelos en la nube para extracciones presupuestarias (QTO), reportes automáticos en Slack/Teams y gestión automatizada del Common Data Environment.",
    methodology: ["Webhooks", "API REST", "BIM Automation"],
    techStack: ["n8n", "Python", "Speckle", "Autodesk Forge / APS"],
    imageUrl: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?q=80&w=2070&auto=format&fit=crop"
  },
  {
    id: "automation-dynamo",
    title: "Desarrollo Visual & Lógica Dynamo",
    category: "Productividad y Auditoría",
    location: "Plataforma Local",
    area: "Lógica Computacional",
    value: "Asset del Departamento",
    description: "Estandarización del departamento mediante la codificación de docenas de scripts complejos en Dynamo/Python orientados a detectar cruces invisibles, renombre masivo MEP y auditoría de integridad del modelo ISO 19650.",
    methodology: ["Algoritmos Genéticos (Generative)", "Lean Construction"],
    techStack: ["Dynamo", "Python node", "Revit API"],
    imageUrl: "https://images.unsplash.com/photo-1550439062-609e1531270e?q=80&w=2070&auto=format&fit=crop"
  }
];

export const portfolioDataEn: PortfolioProject[] = [
  {
    id: "fehmarnbelt",
    title: "Fehmarnbelt Fixed Link Tunnel",
    category: "Heavy Infrastructure",
    location: "Denmark - Germany",
    area: "18 km Length",
    value: "€7.4bn",
    description: "Directed BIM operations for the world's longest immersed tunnel. Managed Open BIM coordination for 22 critical structural segments, reporting directly to IDOM's senior management.",
    methodology: ["ISO 19650", "CDE Management", "Kanban / Agile"],
    techStack: ["Revit", "Navisworks", "Synchro 4D", "BIMcollab"],
    imageUrl: "https://images.unsplash.com/photo-1545139239-e817af750cd5?q=80&w=2070&auto=format&fit=crop"
  },
  {
    id: "data-centers",
    title: "Hyperscale Data Centers",
    category: "Mission Critical / IT",
    location: "Spain / Europe",
    area: "20,000 sqm IT per cluster",
    value: "+€6bn (Regional Program)",
    description: "Production of MEP technical design packages and spatial coordination (LOD 300-350) for Microsoft and Amazon hyperscale clouds, bound by absolute AECOM NDAs and security protocols.",
    methodology: ["MEP Coordination", "Technical Design", "Security Protocols"],
    techStack: ["Revit MEP", "Navisworks", "Python (Scripting)"],
    imageUrl: "https://images.unsplash.com/photo-1558494949-ef010958384e?q=80&w=2000&auto=format&fit=crop"
  },
  {
    id: "camp-nou",
    title: "Spotify Camp Nou Stadium",
    category: "Sports / Stadiums",
    location: "Barcelona, Spain",
    area: "300,000 sqm",
    value: "€1.3bn",
    description: "Led GHESA's on-site architectural modeling team. Orchestrated high-density federated models focused on complex concrete structures during the remodeling of Europe's largest soccer stadium.",
    methodology: ["VDC", "Clash Detection", "ICE Sessions"],
    techStack: ["Revit", "Dynamo", "ACC"],
    imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=2070&auto=format&fit=crop"
  },
  {
    id: "nato-defense",
    title: "NATO Defense Infrastructure",
    category: "Defense / Military",
    location: "Belgium",
    area: "250,000 sqm",
    value: "€800m",
    description: "Rapid-deployment BIM design and spatial coordination under USACE (U.S. Army Corps of Engineers) protocols. Provided rigorous staggered package deliveries across 30/60/90/100% phases.",
    methodology: ["USACE Standards", "Phased Deliverables", "Secure BIM"],
    techStack: ["Revit", "Navisworks", "Secure CDE Platforms"],
    imageUrl: "https://images.unsplash.com/photo-1584462198614-046129841029?q=80&w=2070&auto=format&fit=crop"
  },
  {
    id: "magellan-telescope",
    title: "Giant Magellan Telescope (GMT)",
    category: "Scientific / Heavy Engineering",
    location: "Atacama Desert, Chile (via IDOM)",
    area: "Undisclosed publicly",
    value: "€1.7bn",
    description: "High-precision MEP and architectural coordination solving severe clash constraints required to house massive-scale optics. Operated under relentless schedule constraints.",
    methodology: ["High-Precision VDC", "Clash Resolution System"],
    techStack: ["Revit", "Navisworks", "IT Server Management"],
    imageUrl: "https://images.unsplash.com/photo-1549495689-f55dbbb02a3a?q=80&w=2070&auto=format&fit=crop"
  },
  {
    id: "hospital-orihuela",
    title: "Orihuela Hospital Expansion",
    category: "Healthcare / MEP",
    location: "Alicante, Spain",
    area: "45,000 sqm",
    value: "€70m",
    description: "Sole specialized BIM resource orchestrating the complete HVAC/Fluids scope. Executed rooftop equipment precision modeling and on-site mechanical verification against the federated design.",
    methodology: ["LoIN / BEP", "Federated Workflows", "As-Built Verification"],
    techStack: ["Revit MEP", "Navisworks", "Construction Procurement Data"],
    imageUrl: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=2053&auto=format&fit=crop"
  },
  {
    id: "hospital-donostia",
    title: "Donostia University Hospital",
    category: "Healthcare",
    location: "San Sebastián, Spain",
    area: "Large Scale (~200k sqm Phased)",
    value: "+€250m",
    description: "Architectural alignment and meticulous review of passive health systems under the strict regulations of the Basque Public Health Service (Osakidetza).",
    methodology: ["ISO 19650", "Concurrent Engineering", "Healthcare Norms"],
    techStack: ["Revit Architecture", "Navisworks", "BIM 360 / ACC"],
    imageUrl: "https://images.unsplash.com/photo-1538108149393-fbbd81895907?q=80&w=2000&auto=format&fit=crop"
  },
  {
    id: "hospital-basurto",
    title: "Basurto Hospital",
    category: "Healthcare",
    location: "Bilbao, Spain",
    area: "Large Scale",
    value: "Budget Undisclosed",
    description: "Continuous modernization development demanding persistent MEP and architectural updates. Managed software footprint and bottleneck relief via massive clustered model audits.",
    methodology: ["Data Bottleneck Relief", "BIM Auditing", "QA Governance"],
    techStack: ["Revit", "Navisworks Manage", "Dynamo Graphs"],
    imageUrl: "https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=2074&auto=format&fit=crop"
  },
  {
    id: "hospital-dakar",
    title: "ACH Dakar Hospital Center",
    category: "International Health",
    location: "Dakar, Senegal",
    area: "40,000 sqm",
    value: "€135m",
    description: "Spearheaded complex architectural models from LOD 200 into execution drawings for West African development. Integrated a massive standardized health component repository.",
    methodology: ["Parametric Standardization", "International Delivery"],
    techStack: ["Revit", "Custom Family Libraries"],
    imageUrl: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?q=80&w=2073&auto=format&fit=crop"
  },
  {
    id: "heritage-salamanca",
    title: "Marqués de Salamanca HQ",
    category: "Heritage / Corporate",
    location: "Madrid, Spain",
    area: "25,000 sqm",
    value: "€50m",
    description: "Heritage BIM (HBIM) restructuring of a landmark building. Balanced the integration of hyper-efficient modern MEP routing with absolute preservation requirements governed by historic archives.",
    methodology: ["Heritage BIM (HBIM)", "Scan-to-BIM", "Point Cloud Intel"],
    techStack: ["Revit", "ReCap", "LiDAR Data"],
    imageUrl: "https://images.unsplash.com/photo-1621614050901-71fb264f33b1?q=80&w=2012&auto=format&fit=crop"
  },
  {
    id: "isla-multiespacio",
    title: "Isla Multiespacio High-Rise",
    category: "Mixed-Use / High-Rise",
    location: "Valencia, Venezuela",
    area: "90,000 sqm",
    value: "€150m",
    description: "Comprehensive end-to-end architectural BIM production, actively advising field operations. Navigated severe software disparity via OpenBIM IFC frameworks spanning Revit and ArchiCAD teams.",
    methodology: ["Open BIM", "IFC Interoperability", "Site Supervision"],
    techStack: ["Revit", "ArchiCAD", "V-Ray", "AutoCAD"],
    imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=2070&auto=format&fit=crop"
  },
  {
    id: "automation-n8n",
    title: "Rigid System Automations (n8n/Make)",
    category: "BIM Automation Eng.",
    location: "Cloud Environment",
    area: "Internal Software",
    value: "Integration",
    description: "Pioneered API-based workflows intercepting cloud models to automatically extract budgets (QTOs), push CDE updates, and funnel instant tracking reports to MS Teams and Slack stakeholders.",
    methodology: ["Webhooks", "REST API", "BIM Automation"],
    techStack: ["n8n", "Python", "Speckle", "Autodesk Forge / APS"],
    imageUrl: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?q=80&w=2070&auto=format&fit=crop"
  },
  {
    id: "automation-dynamo",
    title: "Visual Logic & Dynamo Graphing",
    category: "Productivity & Auditing",
    location: "Local Deployments",
    area: "Computational Logic",
    value: "Department Asset",
    description: "Codified department standards by deploying dozens of complex Dynamo/Python scripts to detect stealth clashes, execute massive parametric modifications, and audit ISO 19650 compliant models.",
    methodology: ["Generative / Algorithmic", "Lean Construction"],
    techStack: ["Dynamo", "Python Node", "Revit API"],
    imageUrl: "https://images.unsplash.com/photo-1550439062-609e1531270e?q=80&w=2070&auto=format&fit=crop"
  }
];
